// Дані теми «Рід іменників» — ДЛЯ ПЕРЕВІРКИ ВЧИТЕЛЕМ.
// Формат: { w: слово, g: 'der'|'die'|'das', s?: сигнал закінчення, todo?: причина }
//   g   — рід (означений артикль у Nominativ).
//   s   — сигнал закінчення, якщо він надійно передбачає рід (див. групи нижче).
//   todo — форма сумнівна/регіональна: у гру НЕ потрапляє, поки вчитель не звірить.
//
// Сигнали (SPEC §9): die ← -ung -heit -keit -schaft -ion; der ← -er -ling -ismus;
// das ← -chen -lein -um. Решта — «без сигналу»: рід учиться напам'ять.
//
// Правило чесності: слово потрапляє в сигнальну групу ЛИШЕ якщо сигнал справді
// передбачає його рід. Винятки (das Fenster, die Mutter при -er) — у групі «без сигналу»
// з їхнім справжнім родом. Тест test/genus.test.js машинно звіряє сигнал↔рід і дублікати.
// ~180 найчастотніших іменників A1–A2 (SPEC §9: 150–200).

export default [
  // ─── die-сигнали ────────────────────────────────────────────────
  // -ung → die (від дієслів; завжди die)
  { w: 'Zeitung', g: 'die', s: 'ung' },
  { w: 'Wohnung', g: 'die', s: 'ung' },
  { w: 'Übung', g: 'die', s: 'ung' },
  { w: 'Meinung', g: 'die', s: 'ung' },
  { w: 'Rechnung', g: 'die', s: 'ung' },
  { w: 'Ordnung', g: 'die', s: 'ung' },
  { w: 'Erfahrung', g: 'die', s: 'ung' },
  { w: 'Prüfung', g: 'die', s: 'ung' },
  { w: 'Einladung', g: 'die', s: 'ung' },
  { w: 'Richtung', g: 'die', s: 'ung' },
  // -heit → die
  { w: 'Freiheit', g: 'die', s: 'heit' },
  { w: 'Gesundheit', g: 'die', s: 'heit' },
  { w: 'Krankheit', g: 'die', s: 'heit' },
  { w: 'Wahrheit', g: 'die', s: 'heit' },
  { w: 'Kindheit', g: 'die', s: 'heit' },
  { w: 'Sicherheit', g: 'die', s: 'heit' },
  // -keit → die
  { w: 'Möglichkeit', g: 'die', s: 'keit' },
  { w: 'Schwierigkeit', g: 'die', s: 'keit' },
  { w: 'Fähigkeit', g: 'die', s: 'keit' },
  { w: 'Wirklichkeit', g: 'die', s: 'keit' },
  { w: 'Geschwindigkeit', g: 'die', s: 'keit' },
  // -schaft → die
  { w: 'Freundschaft', g: 'die', s: 'schaft' },
  { w: 'Wissenschaft', g: 'die', s: 'schaft' },
  { w: 'Gesellschaft', g: 'die', s: 'schaft' },
  { w: 'Mannschaft', g: 'die', s: 'schaft' },
  { w: 'Wirtschaft', g: 'die', s: 'schaft' },
  // -ion → die
  { w: 'Nation', g: 'die', s: 'ion' },
  { w: 'Information', g: 'die', s: 'ion' },
  { w: 'Situation', g: 'die', s: 'ion' },
  { w: 'Lektion', g: 'die', s: 'ion' },
  { w: 'Diskussion', g: 'die', s: 'ion' },
  { w: 'Position', g: 'die', s: 'ion' },
  { w: 'Region', g: 'die', s: 'ion' },
  { w: 'Station', g: 'die', s: 'ion' },

  // ─── der-сигнали ────────────────────────────────────────────────
  // -er (діяч/знаряддя) → der. УВАГА: слабкий сигнал — сюди лише надійні der;
  // винятки (das Fenster, die Mutter, das Wasser) — у групі «без сигналу».
  { w: 'Lehrer', g: 'der', s: 'er' },
  { w: 'Schüler', g: 'der', s: 'er' },
  { w: 'Arbeiter', g: 'der', s: 'er' },
  { w: 'Fahrer', g: 'der', s: 'er' },
  { w: 'Spieler', g: 'der', s: 'er' },
  { w: 'Verkäufer', g: 'der', s: 'er' },
  { w: 'Computer', g: 'der', s: 'er' },
  { w: 'Drucker', g: 'der', s: 'er' },
  { w: 'Fernseher', g: 'der', s: 'er' },
  { w: 'Kugelschreiber', g: 'der', s: 'er' },
  // -ling → der
  { w: 'Frühling', g: 'der', s: 'ling' },
  { w: 'Schmetterling', g: 'der', s: 'ling' },
  { w: 'Lehrling', g: 'der', s: 'ling' },
  { w: 'Zwilling', g: 'der', s: 'ling' },
  { w: 'Liebling', g: 'der', s: 'ling' },
  // -ismus → der
  { w: 'Tourismus', g: 'der', s: 'ismus' },
  { w: 'Optimismus', g: 'der', s: 'ismus' },
  { w: 'Journalismus', g: 'der', s: 'ismus' },

  // ─── das-сигнали ────────────────────────────────────────────────
  // -chen → das (зменшувальні)
  { w: 'Mädchen', g: 'das', s: 'chen' },
  { w: 'Brötchen', g: 'das', s: 'chen' },
  { w: 'Märchen', g: 'das', s: 'chen' },
  { w: 'Hähnchen', g: 'das', s: 'chen' },
  { w: 'Kaninchen', g: 'das', s: 'chen' },
  { w: 'Päckchen', g: 'das', s: 'chen' },
  // -lein → das (зменшувальні; рідше в сучасній мові)
  { w: 'Fräulein', g: 'das', s: 'lein' },
  { w: 'Büchlein', g: 'das', s: 'lein' },
  // -um → das
  { w: 'Zentrum', g: 'das', s: 'um' },
  { w: 'Datum', g: 'das', s: 'um' },
  { w: 'Museum', g: 'das', s: 'um' },
  { w: 'Studium', g: 'das', s: 'um' },
  { w: 'Praktikum', g: 'das', s: 'um' },
  { w: 'Album', g: 'das', s: 'um' },

  // ─── без сигналу: рід учиться напам'ять (найбільша група) ────────
  // der
  { w: 'Tisch', g: 'der' },
  { w: 'Stuhl', g: 'der' },
  { w: 'Schrank', g: 'der' },
  { w: 'Mann', g: 'der' },
  { w: 'Junge', g: 'der' },
  { w: 'Vater', g: 'der' },
  { w: 'Bruder', g: 'der' },
  { w: 'Sohn', g: 'der' },
  { w: 'Freund', g: 'der' },
  { w: 'Hund', g: 'der' },
  { w: 'Fisch', g: 'der' },
  { w: 'Baum', g: 'der' },
  { w: 'Berg', g: 'der' },
  { w: 'Himmel', g: 'der' },
  { w: 'Mond', g: 'der' },
  { w: 'Tag', g: 'der' },
  { w: 'Monat', g: 'der' },
  { w: 'Morgen', g: 'der' },
  { w: 'Abend', g: 'der' },
  { w: 'Sommer', g: 'der' },
  { w: 'Winter', g: 'der' },
  { w: 'Zug', g: 'der' },
  { w: 'Bus', g: 'der' },
  { w: 'Garten', g: 'der' },
  { w: 'Schlüssel', g: 'der' },
  { w: 'Kaffee', g: 'der' },
  { w: 'Tee', g: 'der' },
  { w: 'Wein', g: 'der' },
  { w: 'Käse', g: 'der' },
  { w: 'Apfel', g: 'der' },
  { w: 'Salat', g: 'der' },
  { w: 'Kopf', g: 'der' },
  { w: 'Arm', g: 'der' },
  { w: 'Fuß', g: 'der' },
  { w: 'Finger', g: 'der' },
  { w: 'Mund', g: 'der' },
  { w: 'Name', g: 'der' },
  { w: 'Preis', g: 'der' },
  { w: 'Film', g: 'der' },
  { w: 'Schuh', g: 'der' },
  // die
  { w: 'Frau', g: 'die' },
  { w: 'Mutter', g: 'die' },
  { w: 'Tochter', g: 'die' },
  { w: 'Schwester', g: 'die' },
  { w: 'Freundin', g: 'die' },
  { w: 'Katze', g: 'die' },
  { w: 'Blume', g: 'die' },
  { w: 'Tür', g: 'die' },
  { w: 'Wand', g: 'die' },
  { w: 'Lampe', g: 'die' },
  { w: 'Uhr', g: 'die' },
  { w: 'Stadt', g: 'die' },
  { w: 'Straße', g: 'die' },
  { w: 'Insel', g: 'die' },
  { w: 'Sonne', g: 'die' },
  { w: 'Erde', g: 'die' },
  { w: 'Luft', g: 'die' },
  { w: 'Hand', g: 'die' },
  { w: 'Nase', g: 'die' },
  { w: 'Nacht', g: 'die' },
  { w: 'Woche', g: 'die' },
  { w: 'Zeit', g: 'die' },
  { w: 'Stunde', g: 'die' },
  { w: 'Frage', g: 'die' },
  { w: 'Antwort', g: 'die' },
  { w: 'Sprache', g: 'die' },
  { w: 'Arbeit', g: 'die' },
  { w: 'Reise', g: 'die' },
  { w: 'Tasche', g: 'die' },
  { w: 'Hose', g: 'die' },
  { w: 'Jacke', g: 'die' },
  { w: 'Milch', g: 'die' },
  { w: 'Butter', g: 'die' },
  { w: 'Wurst', g: 'die' },
  { w: 'Tomate', g: 'die' },
  { w: 'Schule', g: 'die' },
  { w: 'Klasse', g: 'die' },
  { w: 'Familie', g: 'die' },
  // das
  { w: 'Kind', g: 'das' },
  { w: 'Baby', g: 'das' },
  { w: 'Haus', g: 'das' },
  { w: 'Zimmer', g: 'das' },
  { w: 'Fenster', g: 'das' },
  { w: 'Bett', g: 'das' },
  { w: 'Auto', g: 'das' },
  { w: 'Fahrrad', g: 'das' },
  { w: 'Flugzeug', g: 'das' },
  { w: 'Buch', g: 'das' },
  { w: 'Wort', g: 'das' },
  { w: 'Bild', g: 'das' },
  { w: 'Foto', g: 'das' },
  { w: 'Handy', g: 'das' },
  { w: 'Telefon', g: 'das' },
  { w: 'Geld', g: 'das' },
  { w: 'Wasser', g: 'das' },
  { w: 'Brot', g: 'das' },
  { w: 'Ei', g: 'das' },
  { w: 'Fleisch', g: 'das' },
  { w: 'Gemüse', g: 'das' },
  { w: 'Obst', g: 'das' },
  { w: 'Bier', g: 'das' },
  { w: 'Glas', g: 'das' },
  { w: 'Messer', g: 'das' },
  { w: 'Auge', g: 'das' },
  { w: 'Ohr', g: 'das' },
  { w: 'Bein', g: 'das' },
  { w: 'Herz', g: 'das' },
  { w: 'Haar', g: 'das' },
  { w: 'Gesicht', g: 'das' },
  { w: 'Kleid', g: 'das' },
  { w: 'Jahr', g: 'das' },
  { w: 'Wetter', g: 'das' },
  { w: 'Land', g: 'das' },
  { w: 'Kino', g: 'das' },
  { w: 'Hotel', g: 'das' },
  { w: 'Problem', g: 'das' },
  { w: 'Spiel', g: 'das' },
  { w: 'Tier', g: 'das' },

  // ─── сумнівні/регіональні — у гру НЕ потрапляють, поки вчитель не звірить ──
  { w: 'Joghurt', g: 'der', todo: 'регіонально der/das (Duden подає обидва)' },
  { w: 'Kaugummi', g: 'der', todo: 'регіонально der/das' },
];
