// Дані теми «Wortschatz» (базова лексика) — винесені окремо, ДЛЯ ПЕРЕВІРКИ ВЧИТЕЛЕМ
// (сторінка wortschatz-review.html).
//
// ЧЕСНО ПРО ДЖЕРЕЛО: це ЧАСТОТНА ЛЕКСИКА РІВНЯ A1, складена з пам'яті, а НЕ офіційний
// список Goethe A1. Не подавати як офіційний. Вчитель звіряє (1) рід іменника і
// (2) основне українське значення. Сумнівне позначається `todo` і в гру НЕ потрапляє.
//
// Виключено (вчиться в інших темах, не дублюємо): ~140 іменників із `genus`,
// 49 дієслів із `praesens`/`perfekt`, службові слова (артиклі, займенники, прийменники,
// сполучники, частки).
//
// Формат слова: { de, uk, pos, alt?, accept?, todo? }
//   de     — німецьке слово; іменник ЗАВЖДИ з артиклем (учень так і відповідає: «der Tisch»).
//   uk     — основне українське значення (його бачить учень).
//   pos    — частина мови: 'noun' | 'verb' | 'adj' | 'adv' | 'q'. Вісь карти засвоєння
//            і пул дистракторів (вибір лише зі слів тієї ж частини мови).
//   alt    — інші значення: [{ uk, note? }]. Показуються у фідбеку, у виборі не беруть участі.
//   accept — додаткові приймані форми вводу (крім ä/ae — їх дає srs.normType). Рідко.
//   todo   — сумнівне/поза межами — у гру не йде.
//
// Умлаути при вводі приймаються і як ae/oe/ue/ss (srs.normType), як у praesens.

// ── Частини мови (рядки карти засвоєння) ──────────────────────────────────────
export const POS = [
  { k: 'noun', label: 'іменники',    hint: 'der/die/das' },
  { k: 'verb', label: 'дієслова',    hint: 'Infinitiv' },
  { k: 'adj',  label: 'прикметники', hint: '' },
  { k: 'adv',  label: 'прислівники', hint: '' },
  { k: 'q',    label: 'питальні',    hint: 'W-Fragen' }
];

// ── Сходинки градуйованого відтворення (стовпці карти засвоєння) ───────────────
// Клітинка (частина мови × сходинка N) наливається часткою слів цього класу, що
// ДОСЯГЛИ щонайменше сходинки N (кумулятивно — див. heat.js, SPEC-рішення).
export const STEPS = [
  { k: 0, label: 'впізнавання', hint: 'нім → укр' },
  { k: 1, label: 'з опорою',    hint: 'укр → нім, вибір' },
  { k: 2, label: 'вільно',      hint: 'укр → нім, ввід' }
];

// ── Слова ─────────────────────────────────────────────────────────────────────
export const WORDS = [
  // ── Іменники: der ───────────────────────────────────────────────────────────
  { de: 'der Sommer',      uk: 'літо',            pos: 'noun' },
  { de: 'der Winter',      uk: 'зима',            pos: 'noun' },
  { de: 'der Herbst',      uk: 'осінь',           pos: 'noun' },
  { de: 'der Wald',        uk: 'ліс',             pos: 'noun' },
  { de: 'der Fluss',       uk: 'ріка',            pos: 'noun' },
  { de: 'der Strand',      uk: 'пляж',            pos: 'noun' },
  { de: 'der Regen',       uk: 'дощ',             pos: 'noun' },
  { de: 'der Schnee',      uk: 'сніг',            pos: 'noun' },
  { de: 'der Wind',        uk: 'вітер',           pos: 'noun' },
  { de: 'der Stein',       uk: 'камінь',          pos: 'noun' },
  { de: 'der Markt',       uk: 'ринок',           pos: 'noun' },
  { de: 'der Supermarkt',  uk: 'супермаркет',     pos: 'noun' },
  { de: 'der Laden',       uk: 'крамниця',        pos: 'noun' },
  { de: 'der Kühlschrank', uk: 'холодильник',     pos: 'noun' },
  { de: 'der Teller',      uk: 'тарілка',         pos: 'noun' },
  { de: 'der Löffel',      uk: 'ложка',           pos: 'noun' },
  { de: 'der Fernseher',   uk: 'телевізор',       pos: 'noun' },
  { de: 'der Computer',    uk: "комп'ютер",       pos: 'noun' },
  { de: 'der Spiegel',     uk: 'дзеркало',        pos: 'noun' },
  { de: 'der Teppich',     uk: 'килим',           pos: 'noun' },
  { de: 'der Stift',       uk: 'ручка',           pos: 'noun', alt: [{ uk: 'олівець' }] },
  { de: 'der Koffer',      uk: 'валіза',          pos: 'noun' },
  { de: 'der Rucksack',    uk: 'рюкзак',          pos: 'noun' },
  { de: 'der Regenschirm', uk: 'парасолька',      pos: 'noun' },
  { de: 'der Hut',         uk: 'капелюх',         pos: 'noun' },
  { de: 'der Pullover',    uk: 'светр',           pos: 'noun' },
  { de: 'der Anzug',       uk: 'костюм',          pos: 'noun' },
  { de: 'der Zucker',      uk: 'цукор',           pos: 'noun' },
  { de: 'der Saft',        uk: 'сік',             pos: 'noun' },
  { de: 'der Vogel',       uk: 'птах',            pos: 'noun' },
  { de: 'der Bär',         uk: 'ведмідь',         pos: 'noun' },   // слабкий; відмінювання не тренуємо
  { de: 'der Löwe',        uk: 'лев',             pos: 'noun' },   // слабкий
  { de: 'der Beruf',       uk: 'професія',        pos: 'noun' },
  { de: 'der Chef',        uk: 'начальник',       pos: 'noun' },
  { de: 'der Kollege',     uk: 'колега',          pos: 'noun' },   // слабкий
  { de: 'der Nachbar',     uk: 'сусід',           pos: 'noun' },   // слабкий
  { de: 'der Gast',        uk: 'гість',           pos: 'noun' },
  { de: 'der Körper',      uk: 'тіло',            pos: 'noun' },
  { de: 'der Urlaub',      uk: 'відпустка',       pos: 'noun' },
  { de: 'der Geburtstag',  uk: 'день народження', pos: 'noun' },

  // ── Іменники: die ─────────────────────────────────────────────────────────────
  { de: 'die Wolke',       uk: 'хмара',           pos: 'noun' },
  { de: 'die Pflanze',     uk: 'рослина',         pos: 'noun' },
  { de: 'die Maus',        uk: 'миша',            pos: 'noun' },
  { de: 'die Kuh',         uk: 'корова',          pos: 'noun' },
  { de: 'die Ente',        uk: 'качка',           pos: 'noun' },
  { de: 'die Tür',         uk: 'двері',           pos: 'noun' },
  { de: 'die Küche',       uk: 'кухня',           pos: 'noun' },
  { de: 'die Treppe',      uk: 'сходи',           pos: 'noun' },
  { de: 'die Tasse',       uk: 'чашка',           pos: 'noun' },
  { de: 'die Gabel',       uk: 'виделка',         pos: 'noun' },
  { de: 'die Flasche',     uk: 'пляшка',          pos: 'noun' },
  { de: 'die Dose',        uk: 'банка',           pos: 'noun' },
  { de: 'die Suppe',       uk: 'суп',             pos: 'noun' },
  { de: 'die Schokolade',  uk: 'шоколад',         pos: 'noun' },
  { de: 'die Banane',      uk: 'банан',           pos: 'noun' },
  { de: 'die Birne',       uk: 'груша',           pos: 'noun', alt: [{ uk: 'лампочка' }] },
  { de: 'die Zitrone',     uk: 'лимон',           pos: 'noun' },
  { de: 'die Kartoffel',   uk: 'картопля',        pos: 'noun' },
  { de: 'die Zwiebel',     uk: 'цибуля',          pos: 'noun' },
  { de: 'die Gurke',       uk: 'огірок',          pos: 'noun' },
  { de: 'die Bluse',       uk: 'блузка',          pos: 'noun' },
  { de: 'die Mütze',       uk: 'шапка',           pos: 'noun' },
  { de: 'die Postkarte',   uk: 'листівка',        pos: 'noun' },
  { de: 'die Briefmarke',  uk: 'поштова марка',   pos: 'noun' },
  { de: 'die Nummer',      uk: 'номер',           pos: 'noun' },
  { de: 'die Brücke',      uk: 'міст',            pos: 'noun' },
  { de: 'die Kirche',      uk: 'церква',          pos: 'noun' },
  { de: 'die Apotheke',    uk: 'аптека',          pos: 'noun' },
  { de: 'die Bäckerei',    uk: 'пекарня',         pos: 'noun' },
  { de: 'die Post',        uk: 'пошта',           pos: 'noun' },
  { de: 'die Bank',        uk: 'банк',            pos: 'noun', alt: [{ uk: 'лавка' }] },
  { de: 'die Haltestelle', uk: 'зупинка',         pos: 'noun' },
  { de: 'die Ampel',       uk: 'світлофор',       pos: 'noun' },
  { de: 'die Karte',       uk: 'мапа',            pos: 'noun', alt: [{ uk: 'картка' }, { uk: 'квиток' }] },
  { de: 'die Kasse',       uk: 'каса',            pos: 'noun' },
  { de: 'die Firma',       uk: 'фірма',           pos: 'noun' },
  { de: 'die Universität', uk: 'університет',     pos: 'noun' },
  { de: 'die Note',        uk: 'оцінка',          pos: 'noun', alt: [{ uk: 'нота' }] },
  { de: 'die Aufgabe',     uk: 'завдання',        pos: 'noun' },
  { de: 'die Geschichte',  uk: 'історія',         pos: 'noun' },

  // ── Іменники: das ─────────────────────────────────────────────────────────────
  { de: 'das Pferd',       uk: 'кінь',            pos: 'noun' },
  { de: 'das Schwein',     uk: 'свиня',           pos: 'noun' },
  { de: 'das Schaf',       uk: 'вівця',           pos: 'noun' },
  { de: 'das Huhn',        uk: 'курка',           pos: 'noun' },
  { de: 'das Getränk',     uk: 'напій',           pos: 'noun' },
  { de: 'das Frühstück',   uk: 'сніданок',        pos: 'noun' },
  { de: 'das Mittagessen', uk: 'обід',            pos: 'noun' },
  { de: 'das Abendessen',  uk: 'вечеря',          pos: 'noun' },
  { de: 'das Essen',       uk: 'їжа',             pos: 'noun' },
  { de: 'das Restaurant',  uk: 'ресторан',        pos: 'noun' },
  { de: 'das Café',        uk: 'кафе',            pos: 'noun' },
  { de: 'das Bad',         uk: 'ванна',           pos: 'noun' },
  { de: 'das Schlafzimmer', uk: 'спальня',        pos: 'noun' },
  { de: 'das Wohnzimmer',  uk: 'вітальня',        pos: 'noun' },
  { de: 'das Büro',        uk: 'офіс',            pos: 'noun' },
  { de: 'das Sofa',        uk: 'диван',           pos: 'noun' },
  { de: 'das Regal',       uk: 'полиця',          pos: 'noun' },
  { de: 'das Motorrad',    uk: 'мотоцикл',        pos: 'noun' },
  { de: 'das Schiff',      uk: 'корабель',        pos: 'noun' },
  { de: 'das Ticket',      uk: 'квиток',          pos: 'noun' },
  { de: 'das Gepäck',      uk: 'багаж',           pos: 'noun' },
  { de: 'das Heft',        uk: 'зошит',           pos: 'noun' },
  { de: 'das Papier',      uk: 'папір',           pos: 'noun' },
  { de: 'das Wörterbuch',  uk: 'словник',         pos: 'noun' },
  { de: 'das Internet',    uk: 'інтернет',        pos: 'noun' },
  { de: 'das Geschenk',    uk: 'подарунок',       pos: 'noun' },
  { de: 'das Fest',        uk: 'свято',           pos: 'noun' },
  { de: 'das Lied',        uk: 'пісня',           pos: 'noun' },
  { de: 'das Theater',     uk: 'театр',           pos: 'noun' },
  { de: 'das Konzert',     uk: 'концерт',         pos: 'noun' },
  { de: 'das Krankenhaus', uk: 'лікарня',         pos: 'noun' },
  { de: 'das Dorf',        uk: 'село',            pos: 'noun' },
  { de: 'das Meer',        uk: 'море',            pos: 'noun' },
  { de: 'das Wochenende',  uk: 'вихідні',         pos: 'noun' },
  { de: 'das Stück',       uk: 'шматок',          pos: 'noun' },
  { de: 'das Glück',       uk: 'щастя',           pos: 'noun', alt: [{ uk: 'удача' }] },

  // ── Дієслова ───────────────────────────────────────────────────────────────────
  { de: 'brauchen',    uk: 'потребувати',          pos: 'verb' },
  { de: 'suchen',      uk: 'шукати',               pos: 'verb' },
  { de: 'zeigen',      uk: 'показувати',           pos: 'verb' },
  { de: 'bringen',     uk: 'приносити',            pos: 'verb' },
  { de: 'holen',       uk: 'забирати',             pos: 'verb' },
  { de: 'bezahlen',    uk: 'платити',              pos: 'verb' },
  { de: 'kosten',      uk: 'коштувати',            pos: 'verb' },
  { de: 'bestellen',   uk: 'замовляти',            pos: 'verb' },
  { de: 'öffnen',      uk: 'відчиняти',            pos: 'verb' },
  { de: 'schließen',   uk: 'зачиняти',             pos: 'verb' },
  { de: 'beginnen',    uk: 'починати',             pos: 'verb' },
  { de: 'anfangen',    uk: 'починати',             pos: 'verb' },
  { de: 'warten',      uk: 'чекати',               pos: 'verb' },
  { de: 'leben',       uk: 'жити',                 pos: 'verb' },
  { de: 'treffen',     uk: 'зустрічати',           pos: 'verb' },
  { de: 'besuchen',    uk: 'відвідувати',          pos: 'verb' },
  { de: 'einladen',    uk: 'запрошувати',          pos: 'verb' },
  { de: 'feiern',      uk: 'святкувати',           pos: 'verb' },
  { de: 'tanzen',      uk: 'танцювати',            pos: 'verb' },
  { de: 'singen',      uk: 'співати',              pos: 'verb' },
  { de: 'malen',       uk: 'малювати',             pos: 'verb' },
  { de: 'kochen',      uk: 'готувати (їжу)',       pos: 'verb' },
  { de: 'backen',      uk: 'пекти',                pos: 'verb' },
  { de: 'schmecken',   uk: 'смакувати',            pos: 'verb' },
  { de: 'probieren',   uk: 'куштувати',            pos: 'verb' },
  { de: 'putzen',      uk: 'чистити',              pos: 'verb' },
  { de: 'aufräumen',   uk: 'прибирати',            pos: 'verb' },
  { de: 'anziehen',    uk: 'одягати',              pos: 'verb' },
  { de: 'verkaufen',   uk: 'продавати',            pos: 'verb' },
  { de: 'schenken',    uk: 'дарувати',             pos: 'verb' },
  { de: 'denken',      uk: 'думати',               pos: 'verb' },
  { de: 'glauben',     uk: 'вірити',               pos: 'verb', alt: [{ uk: 'вважати' }] },
  { de: 'wissen',      uk: 'знати (факт)',         pos: 'verb' },
  { de: 'kennen',      uk: 'знати (бути знайомим)', pos: 'verb' },
  { de: 'erklären',    uk: 'пояснювати',           pos: 'verb' },
  { de: 'reden',       uk: 'розмовляти',           pos: 'verb' },
  { de: 'erzählen',    uk: 'розповідати',          pos: 'verb' },
  { de: 'schauen',     uk: 'дивитися',             pos: 'verb' },
  { de: 'üben',        uk: 'вправлятися',          pos: 'verb' },
  { de: 'wiederholen', uk: 'повторювати',          pos: 'verb' },
  { de: 'verdienen',   uk: 'заробляти',            pos: 'verb' },
  { de: 'laufen',      uk: 'бігти',                pos: 'verb', alt: [{ uk: 'іти пішки' }] },
  { de: 'schwimmen',   uk: 'плавати',              pos: 'verb' },
  { de: 'fallen',      uk: 'падати',               pos: 'verb' },
  { de: 'sitzen',      uk: 'сидіти',               pos: 'verb' },
  { de: 'stehen',      uk: 'стояти',               pos: 'verb' },
  { de: 'liegen',      uk: 'лежати',               pos: 'verb' },
  { de: 'legen',       uk: 'класти',               pos: 'verb' },
  { de: 'stellen',     uk: 'ставити',              pos: 'verb' },
  { de: 'telefonieren', uk: 'телефонувати',        pos: 'verb' },
  { de: 'schicken',    uk: 'надсилати',            pos: 'verb' },
  { de: 'gewinnen',    uk: 'вигравати',            pos: 'verb' },
  { de: 'verlieren',   uk: 'програвати',           pos: 'verb', alt: [{ uk: 'втрачати' }] },
  { de: 'lieben',      uk: 'любити',               pos: 'verb' },
  { de: 'lachen',      uk: 'сміятися',             pos: 'verb' },
  { de: 'duschen',     uk: 'приймати душ',         pos: 'verb' },

  // ── Прикметники ──────────────────────────────────────────────────────────────
  { de: 'groß',        uk: 'великий',              pos: 'adj' },
  { de: 'klein',       uk: 'малий',                pos: 'adj' },
  { de: 'lang',        uk: 'довгий',               pos: 'adj' },
  { de: 'kurz',        uk: 'короткий',             pos: 'adj' },
  { de: 'hoch',        uk: 'високий',              pos: 'adj' },
  { de: 'breit',       uk: 'широкий',              pos: 'adj' },
  { de: 'dick',        uk: 'товстий',              pos: 'adj' },
  { de: 'dünn',        uk: 'тонкий',               pos: 'adj' },
  { de: 'alt',         uk: 'старий',               pos: 'adj' },
  { de: 'neu',         uk: 'новий',                pos: 'adj' },
  { de: 'jung',        uk: 'молодий',              pos: 'adj' },
  { de: 'gut',         uk: 'добрий',               pos: 'adj' },
  { de: 'schlecht',    uk: 'поганий',              pos: 'adj' },
  { de: 'schön',       uk: 'гарний',               pos: 'adj' },
  { de: 'schnell',     uk: 'швидкий',              pos: 'adj' },
  { de: 'langsam',     uk: 'повільний',            pos: 'adj' },
  { de: 'früh',        uk: 'ранній',               pos: 'adj' },
  { de: 'spät',        uk: 'пізній',               pos: 'adj' },
  { de: 'teuer',       uk: 'дорогий',              pos: 'adj' },
  { de: 'billig',      uk: 'дешевий',              pos: 'adj' },
  { de: 'reich',       uk: 'багатий',              pos: 'adj' },
  { de: 'arm',         uk: 'бідний',               pos: 'adj' },
  { de: 'warm',        uk: 'теплий',               pos: 'adj' },
  { de: 'kalt',        uk: 'холодний',             pos: 'adj' },
  { de: 'heiß',        uk: 'гарячий',              pos: 'adj' },
  { de: 'nass',        uk: 'мокрий',               pos: 'adj' },
  { de: 'trocken',     uk: 'сухий',                pos: 'adj' },
  { de: 'hell',        uk: 'світлий',              pos: 'adj' },
  { de: 'dunkel',      uk: 'темний',               pos: 'adj' },
  { de: 'laut',        uk: 'гучний',               pos: 'adj' },
  { de: 'leise',       uk: 'тихий',                pos: 'adj' },
  { de: 'sauber',      uk: 'чистий',               pos: 'adj' },
  { de: 'schmutzig',   uk: 'брудний',              pos: 'adj' },
  { de: 'voll',        uk: 'повний',               pos: 'adj' },
  { de: 'leer',        uk: 'порожній',             pos: 'adj' },
  { de: 'richtig',     uk: 'правильний',           pos: 'adj' },
  { de: 'falsch',      uk: 'хибний',               pos: 'adj' },
  { de: 'wichtig',     uk: 'важливий',             pos: 'adj' },
  { de: 'einfach',     uk: 'простий',              pos: 'adj' },
  { de: 'schwierig',   uk: 'складний',             pos: 'adj' },
  { de: 'möglich',     uk: 'можливий',             pos: 'adj' },
  { de: 'frei',        uk: 'вільний',              pos: 'adj' },
  { de: 'müde',        uk: 'втомлений',            pos: 'adj' },
  { de: 'krank',       uk: 'хворий',               pos: 'adj' },
  { de: 'gesund',      uk: 'здоровий',             pos: 'adj' },
  { de: 'hungrig',     uk: 'голодний',             pos: 'adj' },
  { de: 'glücklich',   uk: 'щасливий',             pos: 'adj' },
  { de: 'traurig',     uk: 'сумний',               pos: 'adj' },
  { de: 'freundlich',  uk: 'привітний',            pos: 'adj' },
  { de: 'fertig',      uk: 'готовий',              pos: 'adj' },

  // ── Прислівники ──────────────────────────────────────────────────────────────
  { de: 'heute',       uk: 'сьогодні',             pos: 'adv' },
  { de: 'gestern',     uk: 'вчора',                pos: 'adv' },
  { de: 'morgen',      uk: 'завтра',               pos: 'adv' },
  { de: 'jetzt',       uk: 'зараз',                pos: 'adv' },
  { de: 'bald',        uk: 'скоро',                pos: 'adv' },
  { de: 'immer',       uk: 'завжди',               pos: 'adv' },
  { de: 'oft',         uk: 'часто',                pos: 'adv' },
  { de: 'manchmal',    uk: 'інколи',               pos: 'adv' },
  { de: 'selten',      uk: 'рідко',                pos: 'adv' },
  { de: 'nie',         uk: 'ніколи',               pos: 'adv' },
  { de: 'hier',        uk: 'тут',                  pos: 'adv' },
  { de: 'dort',        uk: 'там',                  pos: 'adv' },
  { de: 'links',       uk: 'ліворуч',              pos: 'adv' },
  { de: 'rechts',      uk: 'праворуч',             pos: 'adv' },
  { de: 'oben',        uk: 'угорі',                pos: 'adv' },
  { de: 'unten',       uk: 'унизу',                pos: 'adv' },
  { de: 'draußen',     uk: 'надворі',              pos: 'adv' },
  { de: 'sehr',        uk: 'дуже',                 pos: 'adv' },
  { de: 'gern',        uk: 'охоче',                pos: 'adv' },
  { de: 'leider',      uk: 'на жаль',              pos: 'adv' },
  { de: 'vielleicht',  uk: 'можливо',              pos: 'adv' },
  { de: 'natürlich',   uk: 'звісно',               pos: 'adv' },
  { de: 'wieder',      uk: 'знову',                pos: 'adv' },
  { de: 'zusammen',    uk: 'разом',                pos: 'adv' },

  // ── Питальні слова ─────────────────────────────────────────────────────────────
  { de: 'wann',        uk: 'коли',                 pos: 'q' },
  { de: 'wo',          uk: 'де',                   pos: 'q' },
  { de: 'wohin',       uk: 'куди',                 pos: 'q' },
  { de: 'woher',       uk: 'звідки',               pos: 'q' },
  { de: 'wie',         uk: 'як',                   pos: 'q' },
  { de: 'warum',       uk: 'чому',                 pos: 'q' }
];

// Артиклі, які можна відділити від іменника (для перевірки вводу: «слово правильне,
// бракує артикля»). Лише Nominativ-форми, бо саме так подано de.
export const ARTICLES = ['der', 'die', 'das'];
